apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    name: simple-webapp
spec:
  containers:
  - name: simple-webapp-container
    image: some-image
    ports:
    - containerPort: 8080
    envFrom:
    - configMapRef:
      name: app-config


# Not sure the above is correct