apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  # set the pod level security context
  securityContext:
    runAsUser: 1000
  containers:
    - name: nginx-container
      image: nginx
      # set the container level security context
      securityContext:
        runAsUser: 1000
        capabilities:
          # drop: ["all"] 
          add: ["MAC_ADMIN"]

# drop all drops all default permissions and they would need to be re-added explicitly
